/**
 * @file      hardware.h (180.ARM_Peripherals/Sources/hardware.h)
 *
 * Main header file for USBDM library.
 * Generated code is included via this file.
 *
 * @version  V4.12.1.270
 * @date     1 December 2021
 */

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#ifndef INCLUDE_USBDM_HARDWARE_H_
#define INCLUDE_USBDM_HARDWARE_H_

#include "error.h"
#include "pin_mapping.h"
#include "delay.h"
#include "console.h"

#include "gpio.h"
#include "spi.h"


namespace USBDM {

/**
 * Map all configured pins to peripheral signals.
 *
 * PCRs of allocated pins are set according to settings in Configure.usbdmProject
 *
 * @note Only the lower 16-bits of the PCR registers are initialised
 */
extern void mapAllPins();

/// SDA_SWD_EN_B
typedef USBDM::GpioA<4,ActiveLow>                            SDA_SWD_EN_B;                                 // PTA4(p16)

/// SDA_RST_TGTMCU_B
typedef USBDM::GpioB<1,ActiveLow>                            SDA_RST_TGTMCU_B;                             // PTB1(p21)

/// SDA_SWD_OE_B
typedef USBDM::GpioB<0,ActiveLow>                            SDA_SWD_OE_B;                                 // PTB0(p20)

/// SDA_SPI0_RST_B (not used)
typedef USBDM::GpioC<1,ActiveHigh>                           SDA_SPI0_RST_B;                               // PTC1(p22)

typedef USBDM::GpioD<7,ActiveLow>                            VTRG_FAULT_B;                                 // PTD7(p32)

/// SDA_LED
typedef USBDM::GpioD<4,ActiveLow>                            SDA_LED;                                      // PTD4(p29)

typedef USBDM::GpioD<6,ActiveHigh>                           POWER_EN;                                     // PTD6(p31)

typedef USBDM::GpioD<5,ActiveHigh>                           SDA_USB_P5V_SENSE;                            // PTD5(p30)

/// User SPI
typedef Spi0                                                 SDA_SPI;                                      

} // End namespace USBDM

#endif /* INCLUDE_USBDM_HARDWARE_H_ */
