#!/bin/bash

HOME_DIR="$(dirname $(readlink -f $0))"
echo HOME_DIR=${HOME_DIR}

VERSION=V4.12.1.330

#***  OpenSDA V1 (P&E)
BOARD_OPENSDA_V1="FRDM-KE02Z FRDM-KE02Z40M FRDM-KE04Z FRDM-KE06Z FRDM-KL02Z FRDM-KL03Z 
                  FRDM-KL05Z FRDM-KL25Z FRDM-KL25Z FRDM-KL26Z FRDM-KL27Z FRDM-KL43Z FRDM-KL46Z FRDM-K20D50M"
#***  OpenSDA V1 + Power (P&E)
BOARD_OPENSDA_V1_POWER="FRDM-KEAZ64Q64 FRDM-KEAZN32Q64 FRDM-KEAZ128Q80 S32K144EVM"
#***  OpenSDA V2
BOARD_OPENSDA_V2="FRDM-KL82Z"
#***  OpenSDA V2 + Power
BOARD_OPENSDA_V2_POWER="FRDM-K64F"
#***  OpenSDA V2.1 + Power
BOARD_OPENSDA_V2_1_POWER="FRDM-K22F FRDM-K28F FRDM-K66F FRDM-K82F FRDM-KV10Z FRDM-KV31F FRDM-KE15Z"

pausing() {
   x=10
   echo -n Pausing ...
   while [ $x -gt 0 ];  do
      sleep 1s
      echo -n " $x"
      x=$(( $x - 1 ))
   done
   echo 
}

CollectFiles() {

clear
echo "***  ****************************************  ***"
echo "***  Collect Firmware files                     ***"
echo "***  ****************************************  ***"

shopt -s nullglob

USBDM_ROOT="$(readlink -f ${HOME_DIR}/../..)"
echo "USBDM_ROOT=${USBDM_ROOT}"

ECLIPSE_ROOT="${USBDM_ROOT}/usbdm-eclipse-makefiles-build"
echo "ECLIPSE_ROOT=${ECLIPSE_ROOT}"

if [[ ! -d ${ECLIPSE_ROOT} ]]; then
   echo "Can't find ECLIPSE_ROOT=${ECLIPSE_ROOT}"
   exit
fi

SOURCE_ROOT="${HOME_DIR}"
FLASH_IMAGES="${ECLIPSE_ROOT}/PackageFiles/FlashImages"
MK_FLASH_DIR="${FLASH_IMAGES}/MKxx"
MK_FLASH_REFERENCE="${MK_FLASH_DIR}/Reference"

echo "MK_FLASH_REFERENCE=${MK_FLASH_REFERENCE}"

mkdir -p ${FLASH_IMAGES}
mkdir -p ${MK_FLASH_DIR}
mkdir -p ${MK_FLASH_REFERENCE}

touch ${MK_FLASH_DIR}/_${VERSION}

echo "***  Doing reference OpenSDA v1"
FIRMWARE_VERSIONS="OpenSDAv1 OpenSDAv1_Power OpenSDAv1_Unique_ID OpenSDAv1_Unique_ID_Power"
for file in ${FIRMWARE_VERSIONS}; do
   cp -p "${SOURCE_ROOT}/${file}/"*.sx "${MK_FLASH_REFERENCE}"
done

echo "***  Doing reference OpenSDA v2"
FIRMWARE_VERSIONS="OpenSDAv2_0 OpenSDAv2_0_Power OpenSDAv2_0_Unique_ID OpenSDAv2_0_Unique_ID_Power OpenSDAv2_1_Power OpenSDAv2_1_Unique_ID_Power" 
for file in ${FIRMWARE_VERSIONS}; do
   cp -p "${SOURCE_ROOT}/${file}/"*.bin "${MK_FLASH_REFERENCE}"
done

echo "***  Doing OpenSDA V1 (P&E)"
echo "${BOARD_OPENSDA_V1}"
for file in ${BOARD_OPENSDA_V1}; do
   cp -p "${SOURCE_ROOT}/OpenSDAv1/"*.sx           "${MK_FLASH_DIR}/${file}.sx"   
   cp -p "${SOURCE_ROOT}/OpenSDAv1_Unique_ID/"*.sx "${MK_FLASH_DIR}/${file}_Unique_ID.sx"
done

echo "***  Doing OpenSDA V1 + Power (P&E)"
BOARD="FRDM-KEAZ64Q64 FRDM-KEAZN32Q64 FRDM-KEAZ128Q80 S32K144EVM"
echo "${BOARD_OPENSDA_V1_POWER}"
for file in ${BOARD_OPENSDA_V1_POWER}; do
   cp -p "${SOURCE_ROOT}/OpenSDAv1_Power/"*.sx           "${MK_FLASH_DIR}/${file}.sx"   
   cp -p "${SOURCE_ROOT}/OpenSDAv1_Unique_ID_Power/"*.sx "${MK_FLASH_DIR}/${file}_Unique_ID.sx"
done

echo "***  Doing OpenSDA V2"
BOARD="FRDM-KL82Z"
echo "${BOARD_OPENSDA_V2}"
for file in ${BOARD_OPENSDA_V2}; do
   cp -p "${SOURCE_ROOT}/OpenSDAv2_0/"*.bin           "${MK_FLASH_DIR}/${file}.bin"   
   cp -p "${SOURCE_ROOT}/OpenSDAv2_0_Unique_ID/"*.bin "${MK_FLASH_DIR}/${file}_Unique_ID.bin"
done

echo "***  Doing OpenSDA V2 + Power"
BOARD="FRDM-K64F"
echo "${BOARD_OPENSDA_V2_POWER}"
for file in ${BOARD_OPENSDA_V2_POWER}; do
   cp -p "${SOURCE_ROOT}/OpenSDAv2_0_Power/"*.bin           "${MK_FLASH_DIR}/${file}.bin"   
   cp -p "${SOURCE_ROOT}/OpenSDAv2_0_Unique_ID_Power/"*.bin "${MK_FLASH_DIR}/${file}_Unique_ID.bin"
done

echo "***  Doing OpenSDA V2.1 + Power"
BOARD="FRDM-K22F FRDM-K28F FRDM-K66F FRDM-K82F FRDM-KV10Z FRDM-KV31F FRDM-KE15Z"
echo "${BOARD_OPENSDA_V2_1_POWER}"
for file in ${BOARD_OPENSDA_V2_1_POWER}; do
   cp -p "${SOURCE_ROOT}/OpenSDAv2_1_Power/"*.bin           "${MK_FLASH_DIR}/${file}.bin"   
   cp -p "${SOURCE_ROOT}/OpenSDAv2_1_Unique_ID_Power/"*.bin "${MK_FLASH_DIR}/${file}_Unique_ID.bin"
done

}

CollectFiles
pausing

exit

