#ifndef _CMDPROCESSINGCFVX_H_
#define _CMDPROCESSINGCFVX_H_

U8 f_CMD_CFVx_RESET(void);
U8 f_CMD_CFVx_CONTROL_INTERFACE(void);
U8 f_CMD_SPI_SET_SPEED(void);
U8 f_CMD_SPI_GET_SPEED(void);

#if (TARGET_CAPABILITY&CAP_CFVx)
U8 f_CMD_CFVx_HALT(void);
U8 f_CMD_CFVx_GO(void);
U8 f_CMD_CFVx_STEP(void);
U8 f_CMD_CFVx_READ_CREG(void);
U8 f_CMD_CFVx_WRITE_CREG(void);
U8 f_CMD_CFVx_READ_DREG(void);
U8 f_CMD_CFVx_READ_STATUS_REG(void);
U8 f_CMD_CFVx_WRITE_DREG(void);
U8 f_CMD_CFVx_READ_REG(void);
U8 f_CMD_CFVx_WRITE_REG(void);
U8 f_CMD_CFVx_READ_MEM(void);
U8 f_CMD_CFVx_WRITE_MEM(void);
U8 f_CMD_CFVx_RESYNC(void);
#endif
#if (TARGET_CAPABILITY&(CAP_DSC|CAP_JTAG|CAP_ARM_JTAG))
U8 f_CMD_JTAG_GOTORESET(void);
U8 f_CMD_JTAG_GOTOSHIFT(void);
U8 f_CMD_JTAG_WRITE(void);
U8 f_CMD_JTAG_READ(void);
U8 f_CMD_JTAG_READ_WRITE(void);
U8 f_CMD_JTAG_EXECUTE_SEQUENCE(void);
U8 f_CMD_JTAG_RESET(void);
#endif // (CAPABILITY&CAP_CFVx)

#endif // _CMDPROCESSINGCFVX_H_
