#ifndef _CMDPROCESSINGCFV1_H_
#define _CMDPROCESSINGCFV1_H_

U8 f_CMD_CF_WRITE_MEM(void);
U8 f_CMD_CF_READ_MEM(void);
U8 f_CMD_CF_WRITE_REG(void);
U8 f_CMD_CF_READ_REG(void);
U8 f_CMD_CF_WRITE_DREG(void);
U8 f_CMD_CF_READ_DREG(void);
U8 f_CMD_CF_WRITE_CREG(void);
U8 f_CMD_CF_READ_CREG(void);
U8 f_CMD_CF_WRITE_CSR2(void);
U8 f_CMD_CF_READ_CSR2(void);
U8 f_CMD_CF_WRITE_CSR3(void);
U8 f_CMD_CF_READ_CSR3(void);

#endif // _CMDPROCESSINGCFV1_H_
