#!/bin/bash

HOME_DIR="$(dirname $(readlink -f $0))"
echo HOME_DIR=${HOME_DIR}

VERSION=V4.12.1.300 

pausing() {
   x=10
   echo -n Pausing ...
   while [ $x -gt 0 ];  do
      sleep 1s
      echo -n " $x"
      x=$(( $x - 1 ))
   done
   echo 
}

CollectFiles() {

clear
echo "***  ****************************************  ***"
echo "***  Collect Firmware files                    ***"
echo "***  ****************************************  ***"

shopt -s nullglob

WORKSPACE="$(readlink -f ${HOME_DIR}/..)"
echo "WORKSPACE=${WORKSPACE}"
USBDM_ROOT="$(readlink -f ${HOME_DIR}/../..)"
echo "USBDM_ROOT=${USBDM_ROOT}"

ECLIPSE_ROOT="${USBDM_ROOT}/usbdm-eclipse-makefiles-build"

SOURCE_ROOT="${HOME_DIR}"
FLASH_IMAGES="${ECLIPSE_ROOT}/PackageFiles/FlashImages"
MK_FLASH_DIR="${FLASH_IMAGES}/MKxx_${VERSION}"
MK_FLASH_REFERENCE="${MK_FLASH_DIR}/Reference"

echo "FLASH_IMAGES=${FLASH_IMAGES}"
echo

mkdir -p ${FLASH_IMAGES}
mkdir -p ${MK_FLASH_DIR}
mkdir -p ${MK_FLASH_REFERENCE}

echo "***  Doing reference OpenSDA v1"
FIRMWARE_VERSIONS="OpenSDAv1 OpenSDAv1_Power OpenSDAv1_Unique_ID OpenSDAv1_Unique_ID_Power"
for file in ${FIRMWARE_VERSIONS}; do
   if ! [ -f "${SOURCE_ROOT}/${file}/"*.sx ]; then
      echo "${SOURCE_ROOT}/${file}/"*.sx not found
      exit
   fi
   cp -p "${SOURCE_ROOT}/${file}/"*.sx "${MK_FLASH_REFERENCE}"
done

echo "***  Doing reference OpenSDA v2"
FIRMWARE_VERSIONS="OpenSDAv2_0 OpenSDAv2_0_Power OpenSDAv2_0_Unique_ID OpenSDAv2_0_Unique_ID_Power OpenSDAv2_1_Power OpenSDAv2_1_Unique_ID_Power" 
for file in ${FIRMWARE_VERSIONS}; do
   if ! [ -f "${SOURCE_ROOT}/${file}/"*.sx ]; then
      echo "${SOURCE_ROOT}/${file}/"*.sx not found
      exit
   fi
   cp -p "${SOURCE_ROOT}/${file}/"*.bin "${MK_FLASH_REFERENCE}"
done

echo "***  Doing OpenSDA V1 (P&E)"
BOARD="FRDM-KE02Z FRDM-KE02Z40M FRDM-KE04Z FRDM-KE06Z FRDM-KL02Z FRDM-KL03Z FRDM-KL05Z FRDM-KL25Z FRDM-KL25Z"
BOARD="${BOARD} FRDM-KL26Z FRDM-KL27Z FRDM-KL43Z FRDM-KL46Z FRDM-K20D50M"

for file in ${BOARD}; do
   if [ -f "${SOURCE_ROOT}/OpenSDAv1/"*.sx ]; then
      cp -p "${SOURCE_ROOT}/OpenSDAv1/"*.sx           "${MK_FLASH_DIR}/${file}.sx"   
   fi
   if [ -f "${SOURCE_ROOT}/OpenSDAv1_Unique_ID/"*.sx ]; then
      cp -p "${SOURCE_ROOT}/OpenSDAv1_Unique_ID/"*.sx "${MK_FLASH_DIR}/${file}_Unique_ID.sx"
   fi
done

echo "***  Doing OpenSDA V1 + Power (P&E)"
BOARD="FRDM-KEAZ64Q64 FRDM-KEAZN32Q64 FRDM-KEAZ128Q80 S32K144EVM"
for file in ${BOARD}; do
    if [ -f "${SOURCE_ROOT}/OpenSDAv1_Power/"*.sx ]; then
       cp -p "${SOURCE_ROOT}/OpenSDAv1_Power/"*.sx           "${MK_FLASH_DIR}/${file}.sx"   
    fi
    if [ -f "${SOURCE_ROOT}/OpenSDAv1_Unique_ID_Power/"*.sx ]; then
       cp -p "${SOURCE_ROOT}/OpenSDAv1_Unique_ID_Power/"*.sx "${MK_FLASH_DIR}/${file}_Unique_ID.sx"
    fi
done

echo "***  Doing OpenSDA V2"
BOARD="FRDM-KL82Z"
for file in ${BOARD}; do
   if [ -f "${SOURCE_ROOT}/OpenSDAv2_0/"*.bin ]; then
      cp -p "${SOURCE_ROOT}/OpenSDAv2_0/"*.bin           "${MK_FLASH_DIR}/${file}.bin"   
   fi
   if [ -f "${SOURCE_ROOT}/OpenSDAv2_0_Unique_ID/"*.bin ]; then
      cp -p "${SOURCE_ROOT}/OpenSDAv2_0_Unique_ID/"*.bin "${MK_FLASH_DIR}/${file}_Unique_ID.bin"
   fi
done

echo "***  Doing OpenSDA V2 + Power"
BOARD="FRDM-K64F"
for file in ${BOARD}; do
   if [ -f "${SOURCE_ROOT}/OpenSDAv2_0_Power/"*.bin ]; then
      cp -p "${SOURCE_ROOT}/OpenSDAv2_0_Power/"*.bin           "${MK_FLASH_DIR}/${file}.bin"   
   fi
   if [ -f "${SOURCE_ROOT}/OpenSDAv2_0_Unique_ID_Power/"*.bin ]; then
      cp -p "${SOURCE_ROOT}/OpenSDAv2_0_Unique_ID_Power/"*.bin "${MK_FLASH_DIR}/${file}_Unique_ID.bin"
   fi
done

echo "***  Doing OpenSDA V2.1 + Power"
BOARD="FRDM-K22F FRDM-K28F FRDM-K66F FRDM-K82F FRDM-KV10Z FRDM-KV31F FRDM-KE15Z FRDM-KW41Z"
for file in ${BOARD}; do
   if [ -f "${SOURCE_ROOT}/OpenSDAv2_1_Power/"*.bin ]; then
      cp -p "${SOURCE_ROOT}/OpenSDAv2_1_Power/"*.bin           "${MK_FLASH_DIR}/${file}.bin"   
   fi
   if [ -f "${SOURCE_ROOT}/OpenSDAv2_1_Power/"*.bin ]; then
      cp -p "${SOURCE_ROOT}/OpenSDAv2_1_Unique_ID_Power/"*.bin "${MK_FLASH_DIR}/${file}_Unique_ID.bin"
   fi
done

echo "***  Doing Bootloop examples"
for file in "${WORKSPACE}/BootLoop"*"/Debug/"*.elf; do
  cp -p "${file}"           "${MK_FLASH_DIR}"   
done

if [ -f "${WORKSPACE}/BootLoopMKL05_SWD_Disabled/"*.md ]; then
   cp -p "${WORKSPACE}/BootLoopMKL05_SWD_Disabled/"*.md "${MK_FLASH_DIR}/ReadMe_BootLoopMKL05_Disable_SWD.txt"
fi

echo "***  Doing bootloader mass erase examples"
for file in "${WORKSPACE}/OpenSDA_MassEraseKinetisTarget/"*/*.sx; do
   cp -p "${WORKSPACE}/OpenSDA_MassEraseKinetisTarget/"*/*.sx "${MK_FLASH_DIR}"
done

for file in "${WORKSPACE}/OpenSDA_MassEraseKinetisTarget/"*/*.bin; do
   cp -p "${WORKSPACE}/OpenSDA_MassEraseKinetisTarget/"*/*.bin "${MK_FLASH_DIR}"
done

if [ -f "${WORKSPACE}/OpenSDA_MassEraseKinetisTarget/"*.md ]; then
   cp -p "${WORKSPACE}/OpenSDA_MassEraseKinetisTarget/"*.md "${MK_FLASH_DIR}/ReadMe_OpenSDA_MassEraseKinetisTarget.txt"
fi


}

clear
CollectFiles
pausing

exit

