/**
 * @file     control.h (180.ARM_Peripherals/Project_Headers/control.h)
 * @brief    CONTROL routines
 *
 * @version  V4.12.1.270
 * @date     20 November 2021
 */
#ifndef HEADER_CONTROL_H
#define HEADER_CONTROL_H
/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

namespace USBDM {

/**
 * @addtogroup Control_Group CONTROL, Control
 * @brief Abstraction for Control
 * @{
 */


/**
 * End CONTROL_Group
 * @}
 */

} // End namespace USBDM

#endif /* HEADER_CONTROL_H */

