################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
ASM_UPPER_SRCS_QUOTED := 
OBJ_SRCS_OS_FORMAT := 
CXX_SRCS := 
CXX_SRCS_QUOTED := 
TODISASSEMBLE_SRCS_OS_FORMAT := 
S_UPPER_SRCS_QUOTED := 
TODISASSEMBLE_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS_QUOTED := 
O_SRCS_OS_FORMAT := 
TOPREPROCESS_SRCS := 
C_SRCS_QUOTED := 
LCF_SRCS := 
CC_SRCS_QUOTED := 
S_SRCS_OS_FORMAT := 
C_UPPER_SRCS := 
O_SRCS_QUOTED := 
C_UPPER_SRCS_QUOTED := 
OBJ_SRCS := 
ASM_SRCS := 
TOPREPROCESS_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS := 
LCF_SRCS_QUOTED := 
ASM_SRCS_OS_FORMAT := 
CXX_SRCS_OS_FORMAT := 
C_SRCS := 
CPP_SRCS_OS_FORMAT := 
S_SRCS := 
CPP_SRCS_QUOTED := 
ASM_SRCS_QUOTED := 
C_UPPER_SRCS_OS_FORMAT := 
CC_SRCS_OS_FORMAT := 
S_SRCS_QUOTED := 
TOPREPROCESS_SRCS_QUOTED := 
ASM_UPPER_SRCS_OS_FORMAT := 
C_SRCS_OS_FORMAT := 
LCF_SRCS_OS_FORMAT := 
TODISASSEMBLE_SRCS_QUOTED := 
S_UPPER_SRCS_OS_FORMAT := 
CC_SRCS := 
ASM_DEPS_OS_FORMAT := 
S_DEPS_QUOTED := 
OBJS := 
EXECUTABLES_OS_FORMAT := 
S_DEPS := 
S_UPPER_DEPS := 
ASM_DEPS := 
CC_DEPS := 
CC_DEPS_QUOTED := 
CPP_DEPS_QUOTED := 
OBJS_QUOTED := 
CPP_DEPS := 
S_UPPER_DEPS_QUOTED := 
EXECUTABLES := 
CXX_DEPS_QUOTED := 
C_DEPS := 
CXX_DEPS_OS_FORMAT := 
CC_DEPS_OS_FORMAT := 
C_UPPER_DEPS_OS_FORMAT := 
ASM_DEPS_QUOTED := 
S_UPPER_DEPS_OS_FORMAT := 
S_DEPS_OS_FORMAT := 
CXX_DEPS := 
ASM_UPPER_DEPS_QUOTED := 
C_UPPER_DEPS_QUOTED := 
CPP_DEPS_OS_FORMAT := 
ASM_UPPER_DEPS := 
ASM_UPPER_DEPS_OS_FORMAT := 
C_DEPS_OS_FORMAT := 
EXECUTABLES_QUOTED := 
C_UPPER_DEPS := 
C_DEPS_QUOTED := 
OBJS_OS_FORMAT := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Sources \
Project_Settings/Startup_Code \
Project_Settings/Linker_Files \

