################################################################################
# Automatically-generated file. Do not edit!
################################################################################

CPP_SRCS := 
ASM_UPPER_SRCS_QUOTED := 
ABS_SRCS_QUOTED := 
OBJ_SRCS_OS_FORMAT := 
CXX_SRCS := 
C++_SRCS_OS_FORMAT := 
CXX_SRCS_QUOTED := 
S_UPPER_SRCS_QUOTED := 
ABS_SRCS := 
TODISASSEMBLE_SRCS_OS_FORMAT := 
S_UPPER_SRCS := 
TODISASSEMBLE_SRCS := 
OBJ_SRCS_QUOTED := 
TOPREPROCESS_SRCS := 
C_SRCS_QUOTED := 
CC_SRCS_QUOTED := 
BBL_SRCS_QUOTED := 
S_SRCS_OS_FORMAT := 
C_UPPER_SRCS := 
C_UPPER_SRCS_QUOTED := 
OBJ_SRCS := 
BBL_SRCS := 
ASM_SRCS := 
TOPREPROCESS_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS := 
C++_SRCS := 
ASM_SRCS_OS_FORMAT := 
BBL_SRCS_OS_FORMAT := 
CXX_SRCS_OS_FORMAT := 
C_SRCS := 
C++_SRCS_QUOTED := 
ABS_SRCS_OS_FORMAT := 
CPP_SRCS_OS_FORMAT := 
S_SRCS := 
CPP_SRCS_QUOTED := 
ASM_SRCS_QUOTED := 
CC_SRCS_OS_FORMAT := 
C_UPPER_SRCS_OS_FORMAT := 
S_SRCS_QUOTED := 
TOPREPROCESS_SRCS_QUOTED := 
ASM_UPPER_SRCS_OS_FORMAT := 
C_SRCS_OS_FORMAT := 
S_UPPER_SRCS_OS_FORMAT := 
TODISASSEMBLE_SRCS_QUOTED := 
CC_SRCS := 
OBJS := 
EXECUTABLES_OS_FORMAT := 
CC_DEPS := 
OBJS_QUOTED := 
CPP_DEPS_QUOTED := 
CC_DEPS_QUOTED := 
BURNER_OUTPUT_OUTPUTS_OS_FORMAT := 
CPP_DEPS := 
EXECUTABLES := 
C++_DEPS_OS_FORMAT := 
CXX_DEPS_QUOTED := 
BURNER_OUTPUT_OUTPUTS := 
C_DEPS := 
CXX_DEPS_OS_FORMAT := 
C_UPPER_DEPS_OS_FORMAT := 
CC_DEPS_OS_FORMAT := 
BURNER_OUTPUT_OUTPUTS_QUOTED := 
CXX_DEPS := 
C++_DEPS := 
C_UPPER_DEPS_QUOTED := 
CPP_DEPS_OS_FORMAT := 
C++_DEPS_QUOTED := 
C_DEPS_OS_FORMAT := 
EXECUTABLES_QUOTED := 
C_UPPER_DEPS := 
C_DEPS_QUOTED := 
OBJS_OS_FORMAT := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Sources \
Project_Settings/Startup_Code \
Project_Settings/Linker_Files \
Lib \

